-- MySQL Script generated by MySQL Workbench
-- Wed Dec  2 22:00:59 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(45) NULL,
  `numero` VARCHAR(10) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` CHAR(2) NULL,
  `cep` CHAR(9) NULL,
  `complemento` VARCHAR(45) NULL,
  PRIMARY KEY (`idPessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa` (
  `idPessoa` INT NOT NULL,
  `Endereco_idPessoa` INT NOT NULL,
  `email` VARCHAR(255) NULL,
  `telefone` VARCHAR(11) NULL,
  `habilitado` ENUM('SIM', 'NAO') NULL,
  `observacoes` TEXT NULL,
  `tipo` ENUM('F', 'J') NULL,
  PRIMARY KEY (`idPessoa`),
  INDEX `fk_Pessoa_Endereco_idx` (`Endereco_idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoa_Endereco`
    FOREIGN KEY (`Endereco_idPessoa`)
    REFERENCES `mydb`.`Endereco` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PessoaFisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PessoaFisica` (
  `idPessoaFisica` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(155) NULL,
  `apelido` VARCHAR(45) NULL,
  `sexo` ENUM('M', 'F') NULL,
  `cpf` VARCHAR(11) NULL,
  `rg` VARCHAR(10) NULL,
  `dataNascimento` DATE NULL,
  `PessoaFisicacol` VARCHAR(45) NULL,
  `Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`idPessoaFisica`),
  INDEX `fk_PessoaFisica_Pessoa1_idx` (`Pessoa_idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_PessoaFisica_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `mydb`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PessoaJuridica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PessoaJuridica` (
  `idPessoaJuridica` INT NOT NULL,
  `razaoSocial` VARCHAR(255) NULL,
  `nomeFantasia` VARCHAR(255) NULL,
  `cnpj` CHAR(14) NULL,
  `ie` CHAR(9) NULL,
  `im` CHAR(11) NULL,
  `Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`idPessoaJuridica`),
  INDEX `fk_PessoaJuridica_Pessoa1_idx` (`Pessoa_idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_PessoaJuridica_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `mydb`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL,
  `senha` VARCHAR(255) NULL,
  `cargo` VARCHAR(45) NULL,
  `nivelDeAcesso` VARCHAR(2) NULL,
  `Pessoa_idPessoa` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Pessoa1_idx` (`Pessoa_idPessoa` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Pessoa1`
    FOREIGN KEY (`Pessoa_idPessoa`)
    REFERENCES `mydb`.`Pessoa` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Venda` (
  `idVenda` INT NOT NULL AUTO_INCREMENT,
  `dataVenda` DATE NULL,
  `precoVenda` DECIMAL(15,2) NULL,
  `desconto` DECIMAL(15,2) NULL,
  `precoTotal` DECIMAL(15,2) NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idVenda`),
  INDEX `fk_Venda_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Venda_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estoque` (
  `idEstoque` INT NOT NULL AUTO_INCREMENT,
  `qtd` INT NULL,
  PRIMARY KEY (`idEstoque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ClienteFisico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ClienteFisico` (
  `idClienteFisico` INT NOT NULL,
  `PessoaFisica_idPessoaFisica` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idClienteFisico`),
  INDEX `fk_ClienteFisico_PessoaFisica1_idx` (`PessoaFisica_idPessoaFisica` ASC) VISIBLE,
  INDEX `fk_ClienteFisico_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_ClienteFisico_PessoaFisica1`
    FOREIGN KEY (`PessoaFisica_idPessoaFisica`)
    REFERENCES `mydb`.`PessoaFisica` (`idPessoaFisica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ClienteFisico_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ClienteJuridico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ClienteJuridico` (
  `idClienteJuridico` INT NOT NULL,
  `PessoaJuridica_idPessoaJuridica` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idClienteJuridico`),
  INDEX `fk_ClienteJuridico_PessoaJuridica1_idx` (`PessoaJuridica_idPessoaJuridica` ASC) VISIBLE,
  INDEX `fk_ClienteJuridico_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_ClienteJuridico_PessoaJuridica1`
    FOREIGN KEY (`PessoaJuridica_idPessoaJuridica`)
    REFERENCES `mydb`.`PessoaJuridica` (`idPessoaJuridica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ClienteJuridico_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Peca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Peca` (
  `idPeca` INT NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `unidadeMedida` VARCHAR(45) NULL,
  `precoCusto` DECIMAL(15,2) NULL,
  `precoVenda` DECIMAL(15,2) NULL,
  `Estoque_idEstoque` INT NOT NULL,
  PRIMARY KEY (`idPeca`),
  INDEX `fk_Peca_Estoque1_idx` (`Estoque_idEstoque` ASC) VISIBLE,
  CONSTRAINT `fk_Peca_Estoque1`
    FOREIGN KEY (`Estoque_idEstoque`)
    REFERENCES `mydb`.`Estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ItensVendidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ItensVendidos` (
  `idItensVendidos` INT NOT NULL AUTO_INCREMENT,
  `Venda_idVenda` INT NOT NULL,
  `Peca_idPeca` INT NOT NULL,
  `qtd` INT NULL,
  PRIMARY KEY (`idItensVendidos`),
  INDEX `fk_ItensVendidos_Venda1_idx` (`Venda_idVenda` ASC) VISIBLE,
  INDEX `fk_ItensVendidos_Peca1_idx` (`Peca_idPeca` ASC) VISIBLE,
  CONSTRAINT `fk_ItensVendidos_Venda1`
    FOREIGN KEY (`Venda_idVenda`)
    REFERENCES `mydb`.`Venda` (`idVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItensVendidos_Peca1`
    FOREIGN KEY (`Peca_idPeca`)
    REFERENCES `mydb`.`Peca` (`idPeca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
